version: '3.8'

services:
  web:
    image: my-node-app
    ports:
      -"8080:3000"
    volumes:
      -./my-node-app:/app
    depends_on:
      - db
    environment:
       POSTGRES_HOST: db
       POSTGRES_USER: myuser
       POSTGRES_PASSWORD: mypassword
       POSTGRES_DB: mydatabase

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
       POSTGRES_USER: myuser
       POSTGRES_PASSWORD: mypassword
       POSTGRES_DB: mydatabase

volumes:
  postgres-data: /var/lib/postgresql/data